In [2]:
import pandas as pd

In [3]:
#read in the data as a dataframe
df = pd.read_excel('formatted data.xlsx')
df.head()

,Age,Island or seamount,Latitude,Longitude,(87Sr/86Sr)measured,(143Nd/144Nd)measured,(176Hf/177Hf)measured,(206Pb/204Pb)measured,(207Pb/204Pb)measured,(208Pb/204Pb)measured,...,Rb/Sr,Nb/Ta,K/Nb,K/U,Pb/Ce,Pb/Th,Hf/Sm,Ti/Gd,K/La,La/Sm
0,NaN,Amsterdam,-37.833,77.551,0.704040,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,St.Paul,-38.727,77.532,0.704400,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,St. Paul,-38.727,77.532,0.703661,0.512896,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,St.Paul,-38.727,77.532,0.704900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,St.Paul,-38.727,77.532,0.704100,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.shape

(13021, 124)

In [5]:
#retrieve the column titles
print(df.columns.to_list())

['Age ', 'Island or seamount', 'Latitude ', 'Longitude ', '(87Sr/86Sr)measured', '(143Nd/144Nd)measured', '(176Hf/177Hf)measured', '(206Pb/204Pb)measured', '(207Pb/204Pb)measured', '(208Pb/204Pb)measured', 'Δ207Pb/204Pbb', 'Δ208Pb/204Pbc', '(206Pb/204Pb)measured.1', '(207Pb/204Pb)measured.1', '(208Pb/204Pb)measured.1', 'δ18Oglass', 'δ18Oolivine', 'δ18Oclinopyroxene', 'δ18Oplagioclase', 'Calculated δ18O of olivine in equilibrium with glassd', 'Calculated δ18O of olivine in equilibrium with clinopyroxenee', 'Calculated δ18O of olivine in equilibrium with plagioclasef', '(187Os/188Os)measured-whole rock', '[Os]whole rock (ppt)', '(187Os/188Os)measured-olivine', '[Os]olivine (ppt)', '(187Os/188Os)measured-clinopyroxene ', '[Os]clinopyroxene (ppt)', 'R/RA', 'R/RA.1', '[4He] (i.e., 10-9 cm3STP/gcrush)', '[4He] (i.e., 10-9 cm3STP/gfusion)', 'He phase', 'SiO2 (wt.%)', 'TiO2 (wt.%)', 'Al2O3 (wt.%)', 'FeOT (wt.%)', 'MnO (wt.%)', 'MgO (wt.%)', 'CaO (wt.%)', 'Na2O (wt.%)', 'K2O (wt.%)', 'P2O5 (wt.%)', 'Total (wt.%)', 'Major phase', 'Method', 'CaO/Al2O3', 'LOI (wt.%)', 'Alkali indexg', 'Li (ppm)', 'Be (ppm)', 'B (ppm)', 'P (ppm)', 'K (ppm)', 'Sc (ppm)', 'Ti (ppm)', 'V (ppm)', 'Cr (ppm)', 'Mn (ppm)', 'Co (ppm)', 'Ni (ppm)', 'Cu (ppm)', 'Zn (ppm)', 'Ga (ppm)', 'Ge (ppm)', 'As (ppm)', 'Se (ppm)', 'Rb (ppm)', 'Sr (ppm)', 'Y (ppm)', 'Zr (ppm)', 'Nb (ppm)', 'Mo (ppm)', 'Cd (ppm)', 'In (ppm)', 'Sn (ppm)', 'Sb (ppm)', 'Te (ppm)', 'Cs (ppm)', 'Ba (ppm)', 'La (ppm)', 'Ce (ppm)', 'Pr (ppm)', 'Nd (ppm)', 'Sm (ppm)', 'Eu (ppm)', 'Gd (ppm)', 'Tb (ppm)', 'Dy (ppm)', 'Ho (ppm)', 'Er (ppm)', 'Tm (ppm)', 'Yb (ppm)', 'Lu (ppm)', 'Hf (ppm)', 'Ta (ppm)', 'W (ppm)', 'Tl (ppm)', 'Pb (ppm)', 'Bi (ppm)', 'Th (ppm)', 'U (ppm)', 'Ba/Rb', 'Th/U', 'Y/Y*h', 'Ce/Ce*i', 'K2O/P2O5', 'Nb/Th', 'Rb/Th', 'Zr/Zr*j', 'Eu/Eu*k', 'Sr/Sr*l', 'Ba/Th', 'Ba/Nb', 'Rb/Sr', 'Nb/Ta', 'K/Nb', 'K/U', 'Pb/Ce', 'Pb/Th', 'Hf/Sm', 'Ti/Gd', 'K/La', 'La/Sm']

In [6]:
df.head()

,Age,Island or seamount,Latitude,Longitude,(87Sr/86Sr)measured,(143Nd/144Nd)measured,(176Hf/177Hf)measured,(206Pb/204Pb)measured,(207Pb/204Pb)measured,(208Pb/204Pb)measured,...,Rb/Sr,Nb/Ta,K/Nb,K/U,Pb/Ce,Pb/Th,Hf/Sm,Ti/Gd,K/La,La/Sm
0,NaN,Amsterdam,-37.833,77.551,0.704040,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,St.Paul,-38.727,77.532,0.704400,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,St. Paul,-38.727,77.532,0.703661,0.512896,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,St.Paul,-38.727,77.532,0.704900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,St.Paul,-38.727,77.532,0.704100,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#creating a dictionary of each title to iterate through next step to find mean per column
column_means = {       
                'Latitude ' : 0 ,
                'Longitude ': 0,
                '(87Sr/86Sr)measured': 0,
                '(143Nd/144Nd)measured': 0, 
                '(176Hf/177Hf)measured': 0, 
                '(206Pb/204Pb)measured': 0, 
                '(207Pb/204Pb)measured': 0,
                '(208Pb/204Pb)measured': 0, 
                'Δ207Pb/204Pbb': 0,
                'Δ208Pb/204Pbc': 0, 
                '(206Pb/204Pb)measured.1': 0,
                '(207Pb/204Pb)measured.1': 0,
                '(208Pb/204Pb)measured.1': 0, 
                'δ18Oglass': 0,
                'δ18Oolivine': 0,
                'δ18Oclinopyroxene': 0,
                'δ18Oplagioclase': 0, 
                'Calculated δ18O of olivine in equilibrium with glassd': 0, 
                'Calculated δ18O of olivine in equilibrium with clinopyroxenee': 0,
                'Calculated δ18O of olivine in equilibrium with plagioclasef': 0, 
                '(187Os/188Os)measured-whole rock': 0,
                '[Os]whole rock (ppt)': 0, 
                '(187Os/188Os)measured-olivine': 0, 
                '[Os]olivine (ppt)': 0, 
                '(187Os/188Os)measured-clinopyroxene ': 0,
                '[Os]clinopyroxene (ppt)': 0, 
                'R/RA': 0, 
                'R/RA.1': 0,
                '[4He] (i.e., 10-9 cm3STP/gcrush)': 0, 
                '[4He] (i.e., 10-9 cm3STP/gfusion)': 0,
                'He phase': 0,
                'SiO2 (wt.%)': 0, 
                'TiO2 (wt.%)': 0, 
                'Al2O3 (wt.%)': 0,
                'FeOT (wt.%)': 0,
                'MnO (wt.%)': 0, 
                'MgO (wt.%)': 0,
                'CaO (wt.%)': 0,
                'Na2O (wt.%)': 0,
                'K2O (wt.%)': 0, 
                'P2O5 (wt.%)': 0, 
                'Total (wt.%)': 0,
                'Major phase': 0, 
                'Method': 0, 
                'CaO/Al2O3': 0, 
                'LOI (wt.%)': 0, 
                'Alkali indexg': 0, 
                'Li (ppm)': 0, 
                'Be (ppm)': 0, 
                'B (ppm)': 0,
                'P (ppm)': 0, 
                'K (ppm)': 0, 
                'Sc (ppm)': 0, 
                'Ti (ppm)': 0, 
                'V (ppm)': 0, 
                'Cr (ppm)': 0, 
                'Mn (ppm)': 0,
                'Co (ppm)': 0,
                'Ni (ppm)': 0,
                'Cu (ppm)': 0, 
                'Zn (ppm)': 0, 
                'Ga (ppm)': 0,
                'Ge (ppm)': 0,
                'As (ppm)': 0, 
                'Se (ppm)': 0,
                'Rb (ppm)': 0,
                'Sr (ppm)': 0, 
                'Y (ppm)': 0, 
                'Zr (ppm)': 0, 
                'Nb (ppm)': 0,
                'Mo (ppm)': 0, 
                'Cd (ppm)': 0,
                'In (ppm)': 0, 
                'Sn (ppm)': 0,
                'Sb (ppm)': 0, 
                'Te (ppm)': 0,
                'Cs (ppm)': 0, 
                'Ba (ppm)': 0,
                'La (ppm)': 0,
                'Ce (ppm)': 0,
                'Pr (ppm)': 0,
                'Nd (ppm)': 0,
                'Sm (ppm)': 0,
                'Eu (ppm)': 0, 
                'Gd (ppm)': 0, 
                'Tb (ppm)': 0,
                'Dy (ppm)': 0,
                'Ho (ppm)': 0, 
                'Er (ppm)': 0, 
                'Tm (ppm)': 0,
                'Yb (ppm)': 0,
                'Lu (ppm)': 0,
                'Hf (ppm)': 0,
                'Ta (ppm)': 0, 
                'W (ppm)': 0,
                'Tl (ppm)': 0,
                'Pb (ppm)': 0,
                'Bi (ppm)': 0, 
                'Th (ppm)': 0,
                'U (ppm)': 0,
                'Ba/Rb': 0,
                'Th/U': 0, 
                'Y/Y*h': 0, 
                'Ce/Ce*i': 0,
                'K2O/P2O5': 0,
                'Nb/Th': 0, 
                'Rb/Th': 0,
                'Zr/Zr*j': 0,
                'Eu/Eu*k': 0,
                'Sr/Sr*l': 0,
                'Ba/Th': 0,
                'Ba/Nb': 0, 
                'Rb/Sr': 0,
                'Nb/Ta': 0, 
                'K/Nb': 0, 
                'K/U': 0,
                'Pb/Ce': 0,
                'Pb/Th': 0, 
                'Hf/Sm': 0, 
                'Ti/Gd': 0, 
                'K/La': 0,
                'La/Sm': 0
                }

In [8]:
#finding mean per column, storing in dictionary from previous step
for key in column_means.keys():
    col_unf = df[key]
    col = pd.to_numeric(col_unf, errors='coerce')
    column_means[key] = col.mean()

In [9]:
column_means

{'Latitude ': np.float64(11.187430283199335),
 'Longitude ': np.float64(-59.903574613785366),
 '(87Sr/86Sr)measured': np.float64(0.7038021525800309),
 '(143Nd/144Nd)measured': np.float64(0.5128910680875117),
 '(176Hf/177Hf)measured': np.float64(0.2830281382419017),
 '(206Pb/204Pb)measured': np.float64(18.828377984641616),
 '(207Pb/204Pb)measured': np.float64(15.546355220390632),
 '(208Pb/204Pb)measured': np.float64(38.67156128335103),
 'Δ207Pb/204Pbb': np.float64(-4.136982554104586),
 'Δ208Pb/204Pbc': np.float64(15.031212837118874),
 '(206Pb/204Pb)measured.1': np.float64(19.03727455680806),
 '(207Pb/204Pb)measured.1': np.float64(15.562317078776738),
 '(208Pb/204Pb)measured.1': np.float64(38.85007118435094),
 'δ18Oglass': np.float64(5.262730726256984),
 'δ18Oolivine': np.float64(4.892935232940008),
 'δ18Oclinopyroxene': np.float64(4.993310924369749),
 'δ18Oplagioclase': np.float64(4.917370860927152),
 'Calculated δ18O of olivine in equilibrium with glassd': np.float64(4.578917142857143),
 'Calculated δ18O of olivine in equilibrium with clinopyroxenee': np.float64(4.523310924369749),
 'Calculated δ18O of olivine in equilibrium with plagioclasef': np.float64(4.237370860927152),
 '(187Os/188Os)measured-whole rock': np.float64(0.14391260173572745),
 '[Os]whole rock (ppt)': np.float64(256.95421300138315),
 '(187Os/188Os)measured-olivine': np.float64(0.13469070175438597),
 '[Os]olivine (ppt)': np.float64(618.8456140350877),
 '(187Os/188Os)measured-clinopyroxene ': np.float64(0.141576875),
 '[Os]clinopyroxene (ppt)': np.float64(187.28571428571428),
 'R/RA': np.float64(12.562252798541763),
 'R/RA.1': np.float64(16.452904543303596),
 '[4He] (i.e., 10-9 cm3STP/gcrush)': np.float64(346.97789972160353),
 '[4He] (i.e., 10-9 cm3STP/gfusion)': np.float64(321.1660562682216),
 'He phase': nan,
 'SiO2 (wt.%)': np.float64(48.11393880854028),
 'TiO2 (wt.%)': np.float64(2.5224770185412226),
 'Al2O3 (wt.%)': np.float64(14.076647753474765),
 'FeOT (wt.%)': np.float64(12.435298418227996),
 'MnO (wt.%)': np.float64(0.18264536991497315),
 'MgO (wt.%)': np.float64(8.239609062504478),
 'CaO (wt.%)': np.float64(9.789918411253364),
 'Na2O (wt.%)': np.float64(3.0461633899267575),
 'K2O (wt.%)': np.float64(1.1693291881643597),
 'P2O5 (wt.%)': np.float64(0.4466309236220558),
 'Total (wt.%)': np.float64(100.0),
 'Major phase': np.float64(1.1027213491759296),
 'Method': nan,
 'CaO/Al2O3': np.float64(0.7256905354622495),
 'LOI (wt.%)': np.float64(1.3852924687677335),
 'Alkali indexg': np.float64(0.5196576290787206),
 'Li (ppm)': np.float64(11.134161042710415),
 'Be (ppm)': np.float64(1.7352216632434518),
 'B (ppm)': np.float64(1.9697948634890814),
 'P (ppm)': np.float64(1057.874772857143),
 'K (ppm)': np.float64(5237.222746),
 'Sc (ppm)': np.float64(27.757083240002366),
 'Ti (ppm)': np.float64(14800.351483049177),
 'V (ppm)': np.float64(259.95416515972926),
 'Cr (ppm)': np.float64(329.71572095985704),
 'Mn (ppm)': np.float64(1437.762582808908),
 'Co (ppm)': np.float64(48.037811143838475),
 'Ni (ppm)': np.float64(181.37977939642755),
 'Cu (ppm)': np.float64(72.52117451889742),
 'Zn (ppm)': np.float64(114.12162323521926),
 'Ga (ppm)': np.float64(21.571812860924602),
 'Ge (ppm)': np.float64(1.5404787841878693),
 'As (ppm)': np.float64(0.9344476549405513),
 'Se (ppm)': np.float64(0.21086328637383178),
 'Rb (ppm)': np.float64(25.1615876693268),
 'Sr (ppm)': np.float64(498.46399120093247),
 'Y (ppm)': np.float64(30.770677950746364),
 'Zr (ppm)': np.float64(242.11669379481168),
 'Nb (ppm)': np.float64(42.26398588622593),
 'Mo (ppm)': np.float64(2.1263192035519056),
 'Cd (ppm)': np.float64(0.1912436986844685),
 'In (ppm)': np.float64(0.1056358126091249),
 'Sn (ppm)': np.float64(2.274711457399308),
 'Sb (ppm)': np.float64(0.1906803216484161),
 'Te (ppm)': np.float64(0.013922351957439525),
 'Cs (ppm)': np.float64(0.371125564589681),
 'Ba (ppm)': np.float64(296.2974043618443),
 'La (ppm)': np.float64(32.33192696319138),
 'Ce (ppm)': np.float64(67.44962754618992),
 'Pr (ppm)': np.float64(8.217871360627132),
 'Nd (ppm)': np.float64(34.24201169270759),
 'Sm (ppm)': np.float64(7.398491671463687),
 'Eu (ppm)': np.float64(2.3336678222370155),
 'Gd (ppm)': np.float64(7.096031137646804),
 'Tb (ppm)': np.float64(1.0566190256133947),
 'Dy (ppm)': np.float64(5.956785546186965),
 'Ho (ppm)': np.float64(1.121160681883774),
 'Er (ppm)': np.float64(2.910728345040772),
 'Tm (ppm)': np.float64(0.4006827211255913),
 'Yb (ppm)': np.float64(2.429121941776556),
 'Lu (ppm)': np.float64(0.3510767403757702),
 'Hf (ppm)': np.float64(5.601585104124062),
 'Ta (ppm)': np.float64(2.6873573142995455),
 'W (ppm)': np.float64(0.6815416361686828),
 'Tl (ppm)': np.float64(0.07837822875840758),
 'Pb (ppm)': np.float64(2.7991837587721706),
 'Bi (ppm)': np.float64(0.027183678424428398),
 'Th (ppm)': np.float64(3.823537618167391),
 'U (ppm)': np.float64(0.9732938791007284),
 'Ba/Rb': np.float64(17.267729229736517),
 'Th/U': np.float64(3.8840986815868326),
 'Y/Y*h': np.float64(1.0232256758853064),
 'Ce/Ce*i': np.float64(1.0320806100561408),
 'K2O/P2O5': np.float64(6.357201784012673),
 'Nb/Th': np.float64(13.327111833670934),
 'Rb/Th': np.float64(7.528239743501994),
 'Zr/Zr*j': np.float64(1.0324104357437316),
 'Eu/Eu*k': np.float64(1.0038146496747844),
 'Sr/Sr*l': np.float64(1.1955678737440678),
 'Ba/Th': np.float64(100.52335223125385),
 'Ba/Nb': np.float64(7.832175283378357),
 'Rb/Sr': np.float64(0.3313522331764804),
 'Nb/Ta': np.float64(16.195025790394748),
 'K/Nb': np.float64(259.52921294486083),
 'K/U': np.float64(11880.715159471867),
 'Pb/Ce': np.float64(0.04172733423801827),
 'Pb/Th': np.float64(1.0274653346170362),
 'Hf/Sm': np.float64(0.7563095702367554),
 'Ti/Gd': np.float64(2290.950936854999),
 'K/La': np.float64(304.5817919967489),
 'La/Sm': np.float64(3.854010374526062)}

In [10]:
#similarly making another dictionary for the entries subtracted from the mean for next step
column_subtracted_means = {       
                'Latitude ' : 0 ,
                'Longitude ': 0,
                '(87Sr/86Sr)measured': 0,
                '(143Nd/144Nd)measured': 0, 
                '(176Hf/177Hf)measured': 0, 
                '(206Pb/204Pb)measured': 0, 
                '(207Pb/204Pb)measured': 0,
                '(208Pb/204Pb)measured': 0, 
                'Δ207Pb/204Pbb': 0,
                'Δ208Pb/204Pbc': 0, 
                '(206Pb/204Pb)measured.1': 0,
                '(207Pb/204Pb)measured.1': 0,
                '(208Pb/204Pb)measured.1': 0, 
                'δ18Oglass': 0,
                'δ18Oolivine': 0,
                'δ18Oclinopyroxene': 0,
                'δ18Oplagioclase': 0, 
                'Calculated δ18O of olivine in equilibrium with glassd': 0, 
                'Calculated δ18O of olivine in equilibrium with clinopyroxenee': 0,
                'Calculated δ18O of olivine in equilibrium with plagioclasef': 0, 
                '(187Os/188Os)measured-whole rock': 0,
                '[Os]whole rock (ppt)': 0, 
                '(187Os/188Os)measured-olivine': 0, 
                '[Os]olivine (ppt)': 0, 
                '(187Os/188Os)measured-clinopyroxene ': 0,
                '[Os]clinopyroxene (ppt)': 0, 
                'R/RA': 0, 
                'R/RA.1': 0,
                '[4He] (i.e., 10-9 cm3STP/gcrush)': 0, 
                '[4He] (i.e., 10-9 cm3STP/gfusion)': 0,
                'He phase': 0,
                'SiO2 (wt.%)': 0, 
                'TiO2 (wt.%)': 0, 
                'Al2O3 (wt.%)': 0,
                'FeOT (wt.%)': 0,
                'MnO (wt.%)': 0, 
                'MgO (wt.%)': 0,
                'CaO (wt.%)': 0,
                'Na2O (wt.%)': 0,
                'K2O (wt.%)': 0, 
                'P2O5 (wt.%)': 0, 
                'Total (wt.%)': 0,
                'Major phase': 0, 
                'Method': 0, 
                'CaO/Al2O3': 0, 
                'LOI (wt.%)': 0, 
                'Alkali indexg': 0, 
                'Li (ppm)': 0, 
                'Be (ppm)': 0, 
                'B (ppm)': 0,
                'P (ppm)': 0, 
                'K (ppm)': 0, 
                'Sc (ppm)': 0, 
                'Ti (ppm)': 0, 
                'V (ppm)': 0, 
                'Cr (ppm)': 0, 
                'Mn (ppm)': 0,
                'Co (ppm)': 0,
                'Ni (ppm)': 0,
                'Cu (ppm)': 0, 
                'Zn (ppm)': 0, 
                'Ga (ppm)': 0,
                'Ge (ppm)': 0,
                'As (ppm)': 0, 
                'Se (ppm)': 0,
                'Rb (ppm)': 0,
                'Sr (ppm)': 0, 
                'Y (ppm)': 0, 
                'Zr (ppm)': 0, 
                'Nb (ppm)': 0,
                'Mo (ppm)': 0, 
                'Cd (ppm)': 0,
                'In (ppm)': 0, 
                'Sn (ppm)': 0,
                'Sb (ppm)': 0, 
                'Te (ppm)': 0,
                'Cs (ppm)': 0, 
                'Ba (ppm)': 0,
                'La (ppm)': 0,
                'Ce (ppm)': 0,
                'Pr (ppm)': 0,
                'Nd (ppm)': 0,
                'Sm (ppm)': 0,
                'Eu (ppm)': 0, 
                'Gd (ppm)': 0, 
                'Tb (ppm)': 0,
                'Dy (ppm)': 0,
                'Ho (ppm)': 0, 
                'Er (ppm)': 0, 
                'Tm (ppm)': 0,
                'Yb (ppm)': 0,
                'Lu (ppm)': 0,
                'Hf (ppm)': 0,
                'Ta (ppm)': 0, 
                'W (ppm)': 0,
                'Tl (ppm)': 0,
                'Pb (ppm)': 0,
                'Bi (ppm)': 0, 
                'Th (ppm)': 0,
                'U (ppm)': 0,
                'Ba/Rb': 0,
                'Th/U': 0, 
                'Y/Y*h': 0, 
                'Ce/Ce*i': 0,
                'K2O/P2O5': 0,
                'Nb/Th': 0, 
                'Rb/Th': 0,
                'Zr/Zr*j': 0,
                'Eu/Eu*k': 0,
                'Sr/Sr*l': 0,
                'Ba/Th': 0,
                'Ba/Nb': 0, 
                'Rb/Sr': 0,
                'Nb/Ta': 0, 
                'K/Nb': 0, 
                'K/U': 0,
                'Pb/Ce': 0,
                'Pb/Th': 0, 
                'Hf/Sm': 0, 
                'Ti/Gd': 0, 
                'K/La': 0,
                'La/Sm': 0
                }

In [11]:
#subtracts the entry from the mean for every datapoint every column, stores back into previous dictionary
for key in column_subtracted_means.keys():
    mean  = column_means[key]
    col = pd.to_numeric(df[key], errors='coerce')
    subtracted_values = []
    for entry in col:
        subtracted_values.append(entry - mean)
    column_subtracted_means[key] = subtracted_values

In [12]:
column_subtracted_means

{'Latitude ': [np.float64(-49.02043028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.02043028319933),
  np.float64(-49.02043028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.02043028319933),
  np.float64(-49.02043028319933),
  np.float64(-49.02043028319933),
  np.float64(-48.707430283199336),
  np.float64(-50.99943028319933),
  np.float64(-51.007430283199334),
  np.float64(-51.39943028319934),
  np.float64(-50.637430283199336),
  np.float64(-50.476430283199335),
  np.float64(-50.40143028319933),
  np.float64(-50.397430283199334),
  np.float64(-50.311430283199336),
  np.float64(-50.14643028319934),
  np.float64(-50.13343028319933),
  np.float64(-49.38643028319933),
  np.float64(-49.16943028319933),
  np.float64(-49.16943028319933),
  np.float64(-48.98943028319933),
  np.float64(-48.765430283199336),
  np.float64(-48.35243028319933),
  np.float64(-48.247430283199336),
  np.float64(-48.24243028319933),
  np.float64(-47.253430283199336),
  np.float64(-47.253430283199336),
  np.float64(-47.257430283199334),
  np.float64(-47.253430283199336),
  np.float64(-46.470430283199335),
  np.float64(-50.86743028319933),
  np.float64(-48.707430283199336),
  np.float64(-50.165430283199335),
  np.float64(-50.144430283199334),
  np.float64(-49.02043028319933),
  np.float64(-49.02043028319933),
  np.float64(-49.02043028319933),
  np.float64(-49.02043028319933),
  np.float64(-49.02043028319933),
  np.float64(-49.02043028319933),
  np.float64(-49.02043028319933),
  np.float64(-49.02043028319933),
  np.float64(-49.02043028319933),
  np.float64(-49.02043028319933),
  np.float64(-49.02043028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.90743028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.91443028319933),
  np.float64(-49.887430283199336),
  np.float64(-49.96843028319933),
  np.float64(-49.62043028319933),
  np.float64(-49.27743028319934),
  np.float64(-49.04743028319933),
  np.float64(-48.308430283199336),
  np.float64(-48.90843028319933),
  np.float64(-48.903430283199334),
  np.float64(-47.36843028319933),
  np.float64(-47.12643028319933),
  np.float64(-46.98443028319933),
  np.float64(-46.827430283199334),
  np.float64(-46.717430283199334),
  np.float64(-48.90843028319933),
  np.float64(-48.903430283199334),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-5.637430283199335),
  np.float64(-5.637430283199335),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-33.60543028319933),
  np.float64(-33.65443028319933),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-30.047430283199333),
  np.float64(-30.025430283199334),
  np.float64(-31.182430283199338),
  np.float64(-31.182430283199338),
  np.float64(-31.183430283199336),
  np.float64(-31.177430283199335),
  np.float64(-31.180430283199335),
  np.float64(-31.177430283199335),
  np.float64(-31.177430283199335),
  np.float64(-31.177430283199335),
  np.float64(-31.177430283199335),
  np.float64(-31.177430283199335),
  np.float64(-31.177430283199335),
  np.float64(-31.177430283199335),
  np.float64(-31.177430283199335),
  np.float64(-31.177430283199335),
  np.float64(-31.177430283199335),
  np.float64(-31.177430283199335),
  np.float64(-31.177430283199335),
  np.float64(-31.177430283199335),
  np.float64(-31.177430283199335),
  np.float64(-31.177430283199335),
  np.float64(-31.177430283199335),
  np.float64(-25.675930283199335),
  np.float64(-25.830730283199337),
  np.float64(-12.327430283199336),
  np.float64(-8.487430283199334),
  np.float64(-15.937430283199335),
  np.float64(-16.847430283199337),
  np.float64(-17.167430283199337),
  np.float64(-19.437430283199333),
  np.float64(-19.847430283199337),
  np.float64(-19.377430283199335),
  np.float64(-18.407430283199336),
  np.float64(-18.407430283199336),
  np.float64(nan),
  np.float64(-19.507430283199334),
  np.float64(-21.497430283199336),
  np.float64(-21.547430283199333),
  np.float64(-21.547430283199333),
  np.float64(-22.517430283199335),
  np.float64(-22.517430283199335),
  np.float64(-33.66743028319934),
  np.float64(-33.66743028319934),
  np.float64(-34.61243028319934),
  np.float64(-34.61243028319934),
  np.float64(-34.61243028319934),
  np.float64(-33.65743028319933),
  np.float64(-25.725130283199334),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(2.7125697168006653),
  np.float64(2.7125697168006653),
  np.float64(2.7125697168006653),
  np.float64(-2.437430283199335),
  np.float64(-2.437430283199335),
  np.float64(-2.437430283199335),
  np.float64(-5.637430283199335),
  np.float64(-5.637430283199335),
  np.float64(-5.637430283199335),
  np.float64(-31.357430283199335),
  np.float64(-31.357430283199335),
  np.float64(-31.357430283199335),
  np.float64(-31.357430283199335),
  np.float64(-31.357430283199335),
  np.float64(-8.697430283199335),
  np.float64(-6.557430283199335),
  np.float64(-12.107430283199335),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-33.665430283199335),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-33.66643028319933),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-33.65743028319933),
  np.float64(-6.937430283199335),
  np.float64(-10.407430283199336),
  np.float64(-21.189430283199336),
  np.float64(-18.587430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.117430283199333),
  np.float64(-19.117430283199333),
  np.float64(-19.117430283199333),
  np.float64(-19.117430283199333),
  np.float64(-19.117430283199333),
  np.float64(-19.117430283199333),
  np.float64(-19.117430283199333),
  np.float64(-19.127430283199335),
  np.float64(-19.117430283199333),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.117430283199333),
  np.float64(-19.127430283199335),
  np.float64(-19.117430283199333),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.167430283199337),
  np.float64(-19.157430283199336),
  np.float64(-19.147430283199334),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(-19.127430283199335),
  np.float64(26.711569716800668),
  np.float64(27.44256971680067),
  np.float64(27.504569716800667),
  np.float64(27.97956971680067),
  np.float64(27.94856971680067),
  np.float64(27.908569716800663),
  np.float64(27.91856971680067),
  np.float64(26.678569716800666),
  np.float64(26.67756971680067),
  np.float64(27.032569716800666),
  np.float64(26.986569716800666),
  np.float64(27.00056971680067),
  np.float64(27.008569716800665),
  np.float64(27.032569716800666),
  np.float64(27.356569716800664),
  np.float64(27.519569716800667),
  np.float64(27.911569716800663),
  np.float64(27.511569716800665),
  np.float64(27.648569716800665),
  np.float64(27.538569716800666),
  np.float64(27.327569716800667),
  np.float64(27.05856971680067),
  np.float64(27.041569716800666),
  np.float64(27.041569716800666),
  np.float64(27.224569716800666),
  np.float64(27.237569716800664),
  np.float64(27.325569716800665),
  np.float64(27.226569716800668),
  np.float64(26.635569716800667),
  np.float64(26.67156971680067),
  np.float64(26.635569716800667),
  np.float64(26.57956971680067),
  np.float64(26.560569716800664),
  np.float64(26.55856971680067),
  np.float64(26.519569716800667),
  np.float64(26.542569716800664),
  np.float64(26.597569716800663),
  np.float64(26.632569716800667),
  np.float64(26.624569716800664),
  np.float64(26.64656971680067),
  np.float64(26.641569716800667),
  np.float64(26.626569716800667),
  np.float64(26.554569716800664),
  np.float64(26.61656971680067),
  np.float64(26.614569716800666),
  np.float64(26.606569716800664),
  np.float64(26.626569716800667),
  np.float64(26.711569716800668),
  np.float64(26.563569716800664),
  np.float64(26.596569716800666),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(27.542569716800664),
  np.float64(27.542569716800664),
  np.float64(27.542569716800664),
  np.float64(27.542569716800664),
  np.float64(27.542569716800664),
  np.float64(27.542569716800664),
  np.float64(27.542569716800664),
  np.float64(27.282569716800666),
  np.float64(27.282569716800666),
  np.float64(27.282569716800666),
  np.float64(27.282569716800666),
  np.float64(27.282569716800666),
  np.float64(26.58256971680067),
  np.float64(27.282569716800666),
  np.float64(27.282569716800666),
  np.float64(27.282569716800666),
  np.float64(27.382569716800667),
  np.float64(27.382569716800667),
  np.float64(27.382569716800667),
  np.float64(27.382569716800667),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(27.542569716800664),
  np.float64(27.542569716800664),
  np.float64(27.382569716800667),
  np.float64(27.382569716800667),
  np.float64(27.382569716800667),
  np.float64(27.87256971680067),
  np.float64(27.282569716800666),
  np.float64(27.282569716800666),
  np.float64(27.282569716800666),
  np.float64(27.462569716800665),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.58256971680067),
  np.float64(26.596569716800666),
  np.float64(26.596569716800666),
  np.float64(27.542569716800664),
  np.float64(27.542569716800664),
  np.float64(27.542569716800664),
  np.float64(27.542569716800664),
  np.float64(27.542569716800664),
  np.float64(27.542569716800664),
  np.float64(26.596569716800666),
  np.float64(26.596569716800666),
  np.float64(26.596569716800666),
  np.float64(26.596569716800666),
  np.float64(26.596569716800666),
  np.float64(26.596569716800666),
  np.float64(27.360469716800665),
  np.float64(27.45136971680067),
  np.float64(27.389869716800668),
  np.float64(27.403569716800668),
  np.float64(27.491869716800664),
  np.float64(27.49418971680067),
  np.float64(27.364969716800665),
  np.float64(27.362769716800663),
  np.float64(27.408869716800666),
  np.float64(27.42846971680067),
  np.float64(27.407169716800666),
  np.float64(27.382569716800667),
  np.float64(27.365369716800664),
  np.float64(27.54596971680067),
  np.float64(27.547169716800667),
  np.float64(27.505669716800668),
  np.float64(27.505669716800668),
  np.float64(27.487169716800665),
  np.float64(27.519869716800663),
  np.float64(27.372669716800665),
  np.float64(27.359569716800664),
  np.float64(27.360769716800668),
  np.float64(27.362869716800667),
  np.float64(27.362769716800663),
  np.float64(26.58256971680067),
  np.float64(27.590569716800665),
  np.float64(27.490569716800664),
  np.float64(27.587569716800665),
  np.float64(27.659569716800668),
  np.float64(27.662569716800668),
  np.float64(27.606569716800664),
  np.float64(28.252569716800664),
  np.float64(28.252569716800664),
  np.float64(28.252569716800664),
  np.float64(27.382569716800667),
  np.float64(27.382569716800667),
  np.float64(27.382569716800667),
  np.float64(27.90556971680067),
  np.float64(27.882569716800667),
  np.float64(27.871569716800664),
  np.float64(27.845569716800668),
  np.float64(27.32956971680067),
  np.float64(27.468569716800666),
  np.float64(27.401569716800665),
  np.float64(27.279569716800665),
  np.float64(27.284569716800668),
  np.float64(27.365569716800664),
  np.float64(27.32956971680067),
  np.float64(27.282569716800666),
  np.float64(27.282569716800666),
  np.float64(27.282569716800666),
  np.float64(27.282569716800666),
  np.float64(27.611569716800666),
  np.float64(27.584569716800665),
  np.float64(27.553569716800666),
  np.float64(27.56456971680067),
  np.float64(27.577569716800667),
  np.float64(27.709569716800665),
  np.float64(27.545569716800664),
  np.float64(28.487769716800663),
  np.float64(28.489169716800667),
  np.float64(28.492769716800666),
  np.float64(28.525369716800668),
  np.float64(28.51766971680067),
  np.float64(28.486169716800667),
  np.float64(28.484369716800664),
  np.float64(28.484369716800664),
  np.float64(28.212569716800665),
  np.float64(28.212569716800665),
  np.float64(27.72786971680067),
  np.float64(27.728569716800664),
  np.float64(27.615169716800665),
  np.float64(27.615169716800665),
  np.float64(27.609869716800667),
  np.float64(27.609769716800663),
  np.float64(27.609169716800665),
  np.float64(27.60846971680067),
  np.float64(27.60756971680067),
  np.float64(27.362569716800664),
  np.float64(27.362569716800664),
  np.float64(27.362569716800664),
  np.float64(27.388569716800667),
  np.float64(27.388569716800667),
  np.float64(27.388569716800667),
  np.float64(27.388569716800667),
  np.float64(27.388569716800667),
  np.float64(27.388569716800667),
  np.float64(27.412569716800668),
  np.float64(27.553569716800666),
  np.float64(27.397569716800668),
  np.float64(27.398569716800665),
  np.float64(27.382569716800667),
  np.float64(27.382569716800667),
  np.float64(27.382569716800667),
  np.float64(27.382569716800667),
  np.float64(27.382569716800667),
  np.float64(27.382569716800667),
  np.float64(27.382569716800667),
  np.float64(27.382569716800667),
  np.float64(27.382569716800667),
  np.float64(28.222569716800663),
  np.float64(28.260569716800667),
  np.float64(28.311069716800667),
  np.float64(28.314869716800665),
  np.float64(28.327469716800664),
  np.float64(28.327469716800664),
  np.float64(28.27066971680067),
  np.float64(28.241069716800666),
  np.float64(28.23516971680067),
  np.float64(28.236969716800665),
  np.float64(28.23496971680067),
  np.float64(28.221969716800665),
  np.float64(28.072569716800665),
  np.float64(28.102569716800666),
  np.float64(28.072569716800665),
  np.float64(28.252569716800664),
  np.float64(27.87256971680067),
  np.float64(27.874569716800664),
  np.float64(27.874569716800664),
  np.float64(27.874569716800664),
  np.float64(27.874569716800664),
  np.float64(27.874569716800664),
  np.float64(27.877569716800664),
  np.float64(27.830569716800667),
  np.float64(27.824569716800667),
  np.float64(27.83556971680067),
  np.float64(27.842569716800668),
  np.float64(27.850569716800663),
  np.float64(27.877569716800664),
  np.float64(27.867569716800666),
  np.float64(27.879569716800667),
  np.float64(27.55556971680067),
  np.float64(27.55556971680067),
  np.float64(27.39056971680067),
  np.float64(27.825569716800665),
  np.float64(27.825569716800665),
  np.float64(27.37856971680067),
  np.float64(27.422569716800666),
  np.float64(27.848569716800668),
  np.float64(26.67156971680067),
  np.float64(26.673569716800664),
  np.float64(26.673569716800664),
  np.float64(26.635569716800667),
  np.float64(27.410569716800666),
  np.float64(27.382569716800667),
  np.float64(27.382569716800667),
  np.float64(27.382569716800667),
  np.float64(26.596569716800666),
  np.float64(26.596569716800666),
  np.float64(27.282569716800666),
  np.float64(27.282569716800666),
  np.float64(27.32956971680067),
  np.float64(27.282569716800666),
  np.float64(27.32956971680067),
  np.float64(27.282569716800666),
  np.float64(27.32956971680067),
  np.float64(27.282569716800666),
  np.float64(27.32956971680067),
  np.float64(27.26256971680067),
  np.float64(27.26256971680067),
  np.float64(27.32956971680067),
  np.float64(27.322569716800665),
  np.float64(27.322569716800665),
  np.float64(27.282569716800666),
  np.float64(27.32956971680067),
  np.float64(27.312569716800667),
  np.float64(27.312569716800667),
  np.float64(27.32956971680067),
  np.float64(27.224569716800666),
  np.float64(27.226569716800668),
  np.float64(27.237569716800664),
  np.float64(27.325569716800665),
  np.float64(27.30556971680067),
  np.float64(27.226569716800668),
  np.float64(27.230569716800666),

In [13]:
import numpy as np

In [14]:
#similarly making, yes,ANOTHER dictionary for the entries subtracted from the mean for next step
#thankfully this file only needs to be run once because yikes 
column_std = {       
                'Latitude ' : 0 ,
                'Longitude ': 0,
                '(87Sr/86Sr)measured': 0,
                '(143Nd/144Nd)measured': 0, 
                '(176Hf/177Hf)measured': 0, 
                '(206Pb/204Pb)measured': 0, 
                '(207Pb/204Pb)measured': 0,
                '(208Pb/204Pb)measured': 0, 
                'Δ207Pb/204Pbb': 0,
                'Δ208Pb/204Pbc': 0, 
                '(206Pb/204Pb)measured.1': 0,
                '(207Pb/204Pb)measured.1': 0,
                '(208Pb/204Pb)measured.1': 0, 
                'δ18Oglass': 0,
                'δ18Oolivine': 0,
                'δ18Oclinopyroxene': 0,
                'δ18Oplagioclase': 0, 
                'Calculated δ18O of olivine in equilibrium with glassd': 0, 
                'Calculated δ18O of olivine in equilibrium with clinopyroxenee': 0,
                'Calculated δ18O of olivine in equilibrium with plagioclasef': 0, 
                '(187Os/188Os)measured-whole rock': 0,
                '[Os]whole rock (ppt)': 0, 
                '(187Os/188Os)measured-olivine': 0, 
                '[Os]olivine (ppt)': 0, 
                '(187Os/188Os)measured-clinopyroxene ': 0,
                '[Os]clinopyroxene (ppt)': 0, 
                'R/RA': 0, 
                'R/RA.1': 0,
                '[4He] (i.e., 10-9 cm3STP/gcrush)': 0, 
                '[4He] (i.e., 10-9 cm3STP/gfusion)': 0,
                'He phase': 0,
                'SiO2 (wt.%)': 0, 
                'TiO2 (wt.%)': 0, 
                'Al2O3 (wt.%)': 0,
                'FeOT (wt.%)': 0,
                'MnO (wt.%)': 0, 
                'MgO (wt.%)': 0,
                'CaO (wt.%)': 0,
                'Na2O (wt.%)': 0,
                'K2O (wt.%)': 0, 
                'P2O5 (wt.%)': 0, 
                'Total (wt.%)': 0,
                'Major phase': 0, 
                'Method': 0, 
                'CaO/Al2O3': 0, 
                'LOI (wt.%)': 0, 
                'Alkali indexg': 0, 
                'Li (ppm)': 0, 
                'Be (ppm)': 0, 
                'B (ppm)': 0,
                'P (ppm)': 0, 
                'K (ppm)': 0, 
                'Sc (ppm)': 0, 
                'Ti (ppm)': 0, 
                'V (ppm)': 0, 
                'Cr (ppm)': 0, 
                'Mn (ppm)': 0,
                'Co (ppm)': 0,
                'Ni (ppm)': 0,
                'Cu (ppm)': 0, 
                'Zn (ppm)': 0, 
                'Ga (ppm)': 0,
                'Ge (ppm)': 0,
                'As (ppm)': 0, 
                'Se (ppm)': 0,
                'Rb (ppm)': 0,
                'Sr (ppm)': 0, 
                'Y (ppm)': 0, 
                'Zr (ppm)': 0, 
                'Nb (ppm)': 0,
                'Mo (ppm)': 0, 
                'Cd (ppm)': 0,
                'In (ppm)': 0, 
                'Sn (ppm)': 0,
                'Sb (ppm)': 0, 
                'Te (ppm)': 0,
                'Cs (ppm)': 0, 
                'Ba (ppm)': 0,
                'La (ppm)': 0,
                'Ce (ppm)': 0,
                'Pr (ppm)': 0,
                'Nd (ppm)': 0,
                'Sm (ppm)': 0,
                'Eu (ppm)': 0, 
                'Gd (ppm)': 0, 
                'Tb (ppm)': 0,
                'Dy (ppm)': 0,
                'Ho (ppm)': 0, 
                'Er (ppm)': 0, 
                'Tm (ppm)': 0,
                'Yb (ppm)': 0,
                'Lu (ppm)': 0,
                'Hf (ppm)': 0,
                'Ta (ppm)': 0, 
                'W (ppm)': 0,
                'Tl (ppm)': 0,
                'Pb (ppm)': 0,
                'Bi (ppm)': 0, 
                'Th (ppm)': 0,
                'U (ppm)': 0,
                'Ba/Rb': 0,
                'Th/U': 0, 
                'Y/Y*h': 0, 
                'Ce/Ce*i': 0,
                'K2O/P2O5': 0,
                'Nb/Th': 0, 
                'Rb/Th': 0,
                'Zr/Zr*j': 0,
                'Eu/Eu*k': 0,
                'Sr/Sr*l': 0,
                'Ba/Th': 0,
                'Ba/Nb': 0, 
                'Rb/Sr': 0,
                'Nb/Ta': 0, 
                'K/Nb': 0, 
                'K/U': 0,
                'Pb/Ce': 0,
                'Pb/Th': 0, 
                'Hf/Sm': 0, 
                'Ti/Gd': 0, 
                'K/La': 0,
                'La/Sm': 0
                }

In [15]:
#finding std per column, storing in dictionary from previous step
for key in column_std.keys():
    col_unf = df[key]
    col = pd.to_numeric(col_unf, errors='coerce')
    column_std[key] = np.std(col)

In [16]:
column_std

{'Latitude ': np.float64(32.21728074313701),
 'Longitude ': np.float64(88.10121951458623),
 '(87Sr/86Sr)measured': np.float64(0.0015873767145417213),
 '(143Nd/144Nd)measured': np.float64(0.0001481433112964647),
 '(176Hf/177Hf)measured': np.float64(0.0001363670192061137),
 '(206Pb/204Pb)measured': np.float64(0.6800093866172653),
 '(207Pb/204Pb)measured': np.float64(0.0762405947285444),
 '(208Pb/204Pb)measured': np.float64(0.6525935495692048),
 'Δ207Pb/204Pbb': np.float64(92.87410371270724),
 'Δ208Pb/204Pbc': np.float64(226.55166044714045),
 '(206Pb/204Pb)measured.1': np.float64(0.722612238721413),
 '(207Pb/204Pb)measured.1': np.float64(0.08015485573404929),
 '(208Pb/204Pb)measured.1': np.float64(0.6566054203729911),
 'δ18Oglass': np.float64(2.3644214665566707),
 'δ18Oolivine': np.float64(0.5016674513974703),
 'δ18Oclinopyroxene': np.float64(0.9963385637312936),
 'δ18Oplagioclase': np.float64(0.9266638560973836),
 'Calculated δ18O of olivine in equilibrium with glassd': np.float64(1.8088236545154681),
 'Calculated δ18O of olivine in equilibrium with clinopyroxenee': np.float64(0.9963385637312936),
 'Calculated δ18O of olivine in equilibrium with plagioclasef': np.float64(0.9266638560973836),
 '(187Os/188Os)measured-whole rock': np.float64(0.0313225684303271),
 '[Os]whole rock (ppt)': np.float64(483.04494062282663),
 '(187Os/188Os)measured-olivine': np.float64(0.007907550213861041),
 '[Os]olivine (ppt)': np.float64(1753.1202647250232),
 '(187Os/188Os)measured-clinopyroxene ': np.float64(0.01024039090364108),
 '[Os]clinopyroxene (ppt)': np.float64(223.42765801786254),
 'R/RA': np.float64(6.682664365451993),
 'R/RA.1': np.float64(14.980488219267205),
 '[4He] (i.e., 10-9 cm3STP/gcrush)': np.float64(1491.8503167740716),
 '[4He] (i.e., 10-9 cm3STP/gfusion)': np.float64(1350.399347497181),
 'He phase': np.float64(nan),
 'SiO2 (wt.%)': np.float64(5.1133039168294125),
 'TiO2 (wt.%)': np.float64(1.0328592315932459),
 'Al2O3 (wt.%)': np.float64(2.526454802217981),
 'FeOT (wt.%)': np.float64(2.7680186065856462),
 'MnO (wt.%)': np.float64(0.040924151152496265),
 'MgO (wt.%)': np.float64(4.649570094669214),
 'CaO (wt.%)': np.float64(2.740803436317008),
 'Na2O (wt.%)': np.float64(1.383159821352037),
 'K2O (wt.%)': np.float64(1.2241081135194434),
 'P2O5 (wt.%)': np.float64(0.3467898684338498),
 'Total (wt.%)': np.float64(1.6679383502713923e-14),
 'Major phase': np.float64(0.40807801357958096),
 'Method': np.float64(nan),
 'CaO/Al2O3': np.float64(0.24650047531262795),
 'LOI (wt.%)': np.float64(1.7823706875317642),
 'Alkali indexg': np.float64(1.8160546688515766),
 'Li (ppm)': np.float64(13.838735164029343),
 'Be (ppm)': np.float64(1.4371086078227264),
 'B (ppm)': np.float64(1.8780226739650194),
 'P (ppm)': np.float64(519.200935367429),
 'K (ppm)': np.float64(2684.5546739890133),
 'Sc (ppm)': np.float64(10.251350254238877),
 'Ti (ppm)': np.float64(6057.2820419610225),
 'V (ppm)': np.float64(89.44930379935559),
 'Cr (ppm)': np.float64(355.3766075287028),
 'Mn (ppm)': np.float64(370.63843369676124),
 'Co (ppm)': np.float64(20.57986502652304),
 'Ni (ppm)': np.float64(207.35540177803506),
 'Cu (ppm)': np.float64(42.281767705540325),
 'Zn (ppm)': np.float64(33.22933660168294),
 'Ga (ppm)': np.float64(5.405120204008666),
 'Ge (ppm)': np.float64(0.38423937582380985),
 'As (ppm)': np.float64(0.44268202998513645),
 'Se (ppm)': np.float64(0.11441574067731813),
 'Rb (ppm)': np.float64(31.191576295033858),
 'Sr (ppm)': np.float64(368.04655650721423),
 'Y (ppm)': np.float64(15.264907006575765),
 'Zr (ppm)': np.float64(192.30963063338416),
 'Nb (ppm)': np.float64(42.32637279220099),
 'Mo (ppm)': np.float64(2.0923538746139476),
 'Cd (ppm)': np.float64(0.2416256130286485),
 'In (ppm)': np.float64(0.04356051282713749),
 'Sn (ppm)': np.float64(1.775339619368362),
 'Sb (ppm)': np.float64(0.44630006843064474),
 'Te (ppm)': np.float64(0.005957905164303335),
 'Cs (ppm)': np.float64(0.6585925457048506),
 'Ba (ppm)': np.float64(299.60843041170386),
 'La (ppm)': np.float64(29.35098339741765),
 'Ce (ppm)': np.float64(53.74371293446874),
 'Pr (ppm)': np.float64(5.950930601057431),
 'Nd (ppm)': np.float64(22.48022662318558),
 'Sm (ppm)': np.float64(3.9665494193961),
 'Eu (ppm)': np.float64(1.0311736946707237),
 'Gd (ppm)': np.float64(3.2494726078408718),
 'Tb (ppm)': np.float64(0.4816841637049834),
 'Dy (ppm)': np.float64(2.712239612712293),
 'Ho (ppm)': np.float64(0.5333419353755443),
 'Er (ppm)': np.float64(1.465441758400565),
 'Tm (ppm)': np.float64(0.21799378265489686),
 'Yb (ppm)': np.float64(1.3428672137910604),
 'Lu (ppm)': np.float64(0.20230522920091373),
 'Hf (ppm)': np.float64(4.126914494444706),
 'Ta (ppm)': np.float64(2.5113814677959767),
 'W (ppm)': np.float64(0.8167302661275344),
 'Tl (ppm)': np.float64(0.14248093668124492),
 'Pb (ppm)': np.float64(3.0580149548712807),
 'Bi (ppm)': np.float64(0.02181790038882073),
 'Th (ppm)': np.float64(4.724722513750897),
 'U (ppm)': np.float64(1.1551511279734334),
 'Ba/Rb': np.float64(18.42703858334986),
 'Th/U': np.float64(2.599986734729131),
 'Y/Y*h': np.float64(0.10275308123486093),
 'Ce/Ce*i': np.float64(0.05807748198978365),
 'K2O/P2O5': np.float64(26.620268297912897),
 'Nb/Th': np.float64(4.315136316170861),
 'Rb/Th': np.float64(7.645531116992579),
 'Zr/Zr*j': np.float64(0.6409581156726316),
 'Eu/Eu*k': np.float64(0.09869443969220813),
 'Sr/Sr*l': np.float64(0.5187600094566961),
 'Ba/Th': np.float64(49.93223645878135),
 'Ba/Nb': np.float64(4.008559284975105),
 'Rb/Sr': np.float64(4.488665559936904),
 'Nb/Ta': np.float64(3.5557884185044397),
 'K/Nb': np.float64(259.28426213359563),
 'K/U': np.float64(7138.757946019664),
 'Pb/Ce': np.float64(0.03728345163134309),
 'Pb/Th': np.float64(1.277159804563558),
 'Hf/Sm': np.float64(0.3997812777806209),
 'Ti/Gd': np.float64(677.3061793701079),
 'K/La': np.float64(217.6273169826049),
 'La/Sm': np.float64(2.1872091943896885)}

In [17]:
#dictionary for the subtracted from mean entries to be divided by std for next step
#this is the last one i promise
column_final = {       
                'Latitude ' : 0 ,
                'Longitude ': 0,
                '(87Sr/86Sr)measured': 0,
                '(143Nd/144Nd)measured': 0, 
                '(176Hf/177Hf)measured': 0, 
                '(206Pb/204Pb)measured': 0, 
                '(207Pb/204Pb)measured': 0,
                '(208Pb/204Pb)measured': 0, 
                'Δ207Pb/204Pbb': 0,
                'Δ208Pb/204Pbc': 0, 
                '(206Pb/204Pb)measured.1': 0,
                '(207Pb/204Pb)measured.1': 0,
                '(208Pb/204Pb)measured.1': 0, 
                'δ18Oglass': 0,
                'δ18Oolivine': 0,
                'δ18Oclinopyroxene': 0,
                'δ18Oplagioclase': 0, 
                'Calculated δ18O of olivine in equilibrium with glassd': 0, 
                'Calculated δ18O of olivine in equilibrium with clinopyroxenee': 0,
                'Calculated δ18O of olivine in equilibrium with plagioclasef': 0, 
                '(187Os/188Os)measured-whole rock': 0,
                '[Os]whole rock (ppt)': 0, 
                '(187Os/188Os)measured-olivine': 0, 
                '[Os]olivine (ppt)': 0, 
                '(187Os/188Os)measured-clinopyroxene ': 0,
                '[Os]clinopyroxene (ppt)': 0, 
                'R/RA': 0, 
                'R/RA.1': 0,
                '[4He] (i.e., 10-9 cm3STP/gcrush)': 0, 
                '[4He] (i.e., 10-9 cm3STP/gfusion)': 0,
                'He phase': 0,
                'SiO2 (wt.%)': 0, 
                'TiO2 (wt.%)': 0, 
                'Al2O3 (wt.%)': 0,
                'FeOT (wt.%)': 0,
                'MnO (wt.%)': 0, 
                'MgO (wt.%)': 0,
                'CaO (wt.%)': 0,
                'Na2O (wt.%)': 0,
                'K2O (wt.%)': 0, 
                'P2O5 (wt.%)': 0, 
                'Total (wt.%)': 0,
                'Major phase': 0, 
                'Method': 0, 
                'CaO/Al2O3': 0, 
                'LOI (wt.%)': 0, 
                'Alkali indexg': 0, 
                'Li (ppm)': 0, 
                'Be (ppm)': 0, 
                'B (ppm)': 0,
                'P (ppm)': 0, 
                'K (ppm)': 0, 
                'Sc (ppm)': 0, 
                'Ti (ppm)': 0, 
                'V (ppm)': 0, 
                'Cr (ppm)': 0, 
                'Mn (ppm)': 0,
                'Co (ppm)': 0,
                'Ni (ppm)': 0,
                'Cu (ppm)': 0, 
                'Zn (ppm)': 0, 
                'Ga (ppm)': 0,
                'Ge (ppm)': 0,
                'As (ppm)': 0, 
                'Se (ppm)': 0,
                'Rb (ppm)': 0,
                'Sr (ppm)': 0, 
                'Y (ppm)': 0, 
                'Zr (ppm)': 0, 
                'Nb (ppm)': 0,
                'Mo (ppm)': 0, 
                'Cd (ppm)': 0,
                'In (ppm)': 0, 
                'Sn (ppm)': 0,
                'Sb (ppm)': 0, 
                'Te (ppm)': 0,
                'Cs (ppm)': 0, 
                'Ba (ppm)': 0,
                'La (ppm)': 0,
                'Ce (ppm)': 0,
                'Pr (ppm)': 0,
                'Nd (ppm)': 0,
                'Sm (ppm)': 0,
                'Eu (ppm)': 0, 
                'Gd (ppm)': 0, 
                'Tb (ppm)': 0,
                'Dy (ppm)': 0,
                'Ho (ppm)': 0, 
                'Er (ppm)': 0, 
                'Tm (ppm)': 0,
                'Yb (ppm)': 0,
                'Lu (ppm)': 0,
                'Hf (ppm)': 0,
                'Ta (ppm)': 0, 
                'W (ppm)': 0,
                'Tl (ppm)': 0,
                'Pb (ppm)': 0,
                'Bi (ppm)': 0, 
                'Th (ppm)': 0,
                'U (ppm)': 0,
                'Ba/Rb': 0,
                'Th/U': 0, 
                'Y/Y*h': 0, 
                'Ce/Ce*i': 0,
                'K2O/P2O5': 0,
                'Nb/Th': 0, 
                'Rb/Th': 0,
                'Zr/Zr*j': 0,
                'Eu/Eu*k': 0,
                'Sr/Sr*l': 0,
                'Ba/Th': 0,
                'Ba/Nb': 0, 
                'Rb/Sr': 0,
                'Nb/Ta': 0, 
                'K/Nb': 0, 
                'K/U': 0,
                'Pb/Ce': 0,
                'Pb/Th': 0, 
                'Hf/Sm': 0, 
                'Ti/Gd': 0, 
                'K/La': 0,
                'La/Sm': 0
                }

In [18]:
#divides the subtracted mean by the std for every datapoint every column, stores back into previous dictionary
for key in column_final.keys():
    std  = column_std[key]
    final_values = []
    col_sub= np.asarray(column_subtracted_means[key], dtype=np.float64)
    for entry in col_sub:
        final_values.append(entry/std)
    column_final[key] = final_values

In [19]:
#yippeee nondimensionalized data
column_final

{'Latitude ': [np.float64(-1.5215570387218904),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.5215570387218904),
  np.float64(-1.5215570387218904),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.5215570387218904),
  np.float64(-1.5215570387218904),
  np.float64(-1.5215570387218904),
  np.float64(-1.5118417557190977),
  np.float64(-1.5829837002635094),
  np.float64(-1.583232014206073),
  np.float64(-1.5953993973916791),
  np.float64(-1.571747494362516),
  np.float64(-1.5667501762684277),
  np.float64(-1.564422233056896),
  np.float64(-1.5642980760856142),
  np.float64(-1.5616287012030579),
  np.float64(-1.556507226137688),
  np.float64(-1.5561037159810223),
  np.float64(-1.5329174015941656),
  np.float64(-1.5261818859021334),
  np.float64(-1.5261818859021334),
  np.float64(-1.5205948221944572),
  np.float64(-1.5136420318026824),
  np.float64(-1.5008228245178472),
  np.float64(-1.4975637040217027),
  np.float64(-1.4974085078076005),
  np.float64(-1.4667106966582013),
  np.float64(-1.4667106966582013),
  np.float64(-1.4668348536294828),
  np.float64(-1.4667106966582013),
  np.float64(-1.4424069695298092),
  np.float64(-1.5788865202112135),
  np.float64(-1.5118417557190977),
  np.float64(-1.557096971751276),
  np.float64(-1.556445147652047),
  np.float64(-1.5215570387218904),
  np.float64(-1.5215570387218904),
  np.float64(-1.5215570387218904),
  np.float64(-1.5215570387218904),
  np.float64(-1.5215570387218904),
  np.float64(-1.5215570387218904),
  np.float64(-1.5215570387218904),
  np.float64(-1.5215570387218904),
  np.float64(-1.5215570387218904),
  np.float64(-1.5215570387218904),
  np.float64(-1.5215570387218904),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.5490888471036064),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.5493061218033493),
  np.float64(-1.548468062247198),
  np.float64(-1.5509822409156524),
  np.float64(-1.5401805844141447),
  np.float64(-1.5295341241267395),
  np.float64(-1.5223950982780419),
  np.float64(-1.4994570978337485),
  np.float64(-1.5180806435260028),
  np.float64(-1.5179254473119008),
  np.float64(-1.4702802095825498),
  np.float64(-1.4627687128200073),
  np.float64(-1.458361140339507),
  np.float64(-1.4534879792167006),
  np.float64(-1.4500736625064539),
  np.float64(-1.5180806435260028),
  np.float64(-1.5179254473119008),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-0.17498156744343582),
  np.float64(-0.17498156744343582),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-1.0430871106450543),
  np.float64(-1.044608033543255),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-0.9326494846899858),
  np.float64(-0.9319666213479364),
  np.float64(-0.9678790252911671),
  np.float64(-0.9678790252911671),
  np.float64(-0.9679100645339874),
  np.float64(-0.9677238290770649),
  np.float64(-0.9678169468055262),
  np.float64(-0.9677238290770649),
  np.float64(-0.9677238290770649),
  np.float64(-0.9677238290770649),
  np.float64(-0.9677238290770649),
  np.float64(-0.9677238290770649),
  np.float64(-0.9677238290770649),
  np.float64(-0.9677238290770649),
  np.float64(-0.9677238290770649),
  np.float64(-0.9677238290770649),
  np.float64(-0.9677238290770649),
  np.float64(-0.9677238290770649),
  np.float64(-0.9677238290770649),
  np.float64(-0.9677238290770649),
  np.float64(-0.9677238290770649),
  np.float64(-0.9677238290770649),
  np.float64(-0.9677238290770649),
  np.float64(-0.7969614347005023),
  np.float64(-0.801766309489104),
  np.float64(-0.3826341019120724),
  np.float64(-0.2634434094816442),
  np.float64(-0.4946857684938031),
  np.float64(-0.522931479460389),
  np.float64(-0.5328640371629246),
  np.float64(-0.6033231183652871),
  np.float64(-0.616049207921661),
  np.float64(-0.6014607637960616),
  np.float64(-0.5713526982602504),
  np.float64(-0.5713526982602504),
  np.float64(nan),
  np.float64(-0.6054958653627167),
  np.float64(-0.6672639585753606),
  np.float64(-0.6688159207163816),
  np.float64(-0.6688159207163816),
  np.float64(-0.698923986252193),
  np.float64(-0.698923986252193),
  np.float64(-1.0450115436999208),
  np.float64(-1.0450115436999208),
  np.float64(-1.0743436281652214),
  np.float64(-1.0743436281652214),
  np.float64(-1.0743436281652214),
  np.float64(-1.0447011512717164),
  np.float64(-0.7984885654472671),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(0.08419611010710462),
  np.float64(0.08419611010710462),
  np.float64(0.08419611010710462),
  np.float64(-0.07565599041807901),
  np.float64(-0.07565599041807901),
  np.float64(-0.07565599041807901),
  np.float64(-0.17498156744343582),
  np.float64(-0.17498156744343582),
  np.float64(-0.17498156744343582),
  np.float64(-0.9733108927847413),
  np.float64(-0.9733108927847413),
  np.float64(-0.9733108927847413),
  np.float64(-0.9733108927847413),
  np.float64(-0.9733108927847413),
  np.float64(-0.2699616504739333),
  np.float64(-0.2035376708382259),
  np.float64(-0.37580546849157914),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-1.04494946521428),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-1.0449805044571001),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-1.0447011512717164),
  np.float64(-0.21533258310998704),
  np.float64(-0.32303875569685836),
  np.float64(-0.65770387178667),
  np.float64(-0.5769397619679267),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5933905606627513),
  np.float64(-0.5933905606627513),
  np.float64(-0.5933905606627513),
  np.float64(-0.5933905606627513),
  np.float64(-0.5933905606627513),
  np.float64(-0.5933905606627513),
  np.float64(-0.5933905606627513),
  np.float64(-0.5937009530909556),
  np.float64(-0.5933905606627513),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5933905606627513),
  np.float64(-0.5937009530909556),
  np.float64(-0.5933905606627513),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5949425228037727),
  np.float64(-0.5946321303755684),
  np.float64(-0.5943217379473641),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(-0.5937009530909556),
  np.float64(0.8291068985544604),
  np.float64(0.8517965850561904),
  np.float64(0.8537210181110566),
  np.float64(0.868464658450758),
  np.float64(0.8675024419233249),
  np.float64(0.8662608722105078),
  np.float64(0.8665712646387121),
  np.float64(0.8280826035413864),
  np.float64(0.828051564298566),
  np.float64(0.8390704954998164),
  np.float64(0.837642690330077),
  np.float64(0.8380772397295629),
  np.float64(0.8383255536721262),
  np.float64(0.8390704954998164),
  np.float64(0.8491272101736338),
  np.float64(0.854186606753363),
  np.float64(0.8663539899389691),
  np.float64(0.8539382928107995),
  np.float64(0.8581906690771977),
  np.float64(0.854776352366951),
  np.float64(0.8482270721318416),
  np.float64(0.8398775158131475),
  np.float64(0.8393498486852002),
  np.float64(0.8393498486852002),
  np.float64(0.8450300301213378),
  np.float64(0.8454335402780033),
  np.float64(0.8481649936462007),
  np.float64(0.8450921086069788),
  np.float64(0.8267479161001081),
  np.float64(0.8278653288416434),
  np.float64(0.8267479161001081),
  np.float64(0.8250097185021645),
  np.float64(0.8244199728885763),
  np.float64(0.8243578944029356),
  np.float64(0.823147363932939),
  np.float64(0.8238612665178087),
  np.float64(0.8255684248729319),
  np.float64(0.8266547983716469),
  np.float64(0.8264064844290834),
  np.float64(0.8270893477711329),
  np.float64(0.8269341515570308),
  np.float64(0.8264685629147244),
  np.float64(0.8242337374316537),
  np.float64(0.8261581704865202),
  np.float64(0.8260960920008792),
  np.float64(0.8258477780583158),
  np.float64(0.8264685629147244),
  np.float64(0.8291068985544604),
  np.float64(0.8245130906170376),
  np.float64(0.8255373856301116),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8549005093382326),
  np.float64(0.8549005093382326),
  np.float64(0.8549005093382326),
  np.float64(0.8549005093382326),
  np.float64(0.8549005093382326),
  np.float64(0.8549005093382326),
  np.float64(0.8549005093382326),
  np.float64(0.8468303062049224),
  np.float64(0.8468303062049224),
  np.float64(0.8468303062049224),
  np.float64(0.8468303062049224),
  np.float64(0.8468303062049224),
  np.float64(0.8251028362306257),
  np.float64(0.8468303062049224),
  np.float64(0.8468303062049224),
  np.float64(0.8468303062049224),
  np.float64(0.8499342304869649),
  np.float64(0.8499342304869649),
  np.float64(0.8499342304869649),
  np.float64(0.8499342304869649),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8549005093382326),
  np.float64(0.8549005093382326),
  np.float64(0.8499342304869649),
  np.float64(0.8499342304869649),
  np.float64(0.8499342304869649),
  np.float64(0.8651434594689728),
  np.float64(0.8468303062049224),
  np.float64(0.8468303062049224),
  np.float64(0.8468303062049224),
  np.float64(0.8524173699125988),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8251028362306257),
  np.float64(0.8255373856301116),
  np.float64(0.8255373856301116),
  np.float64(0.8549005093382326),
  np.float64(0.8549005093382326),
  np.float64(0.8549005093382326),
  np.float64(0.8549005093382326),
  np.float64(0.8549005093382326),
  np.float64(0.8549005093382326),
  np.float64(0.8255373856301116),
  np.float64(0.8255373856301116),
  np.float64(0.8255373856301116),
  np.float64(0.8255373856301116),
  np.float64(0.8255373856301116),
  np.float64(0.8255373856301116),
  np.float64(0.8492482632206334),
  np.float64(0.8520697303930101),
  np.float64(0.850160816959554),
  np.float64(0.8505860545861939),
  np.float64(0.8533268197272371),
  np.float64(0.8533988307705807),
  np.float64(0.8493879398133254),
  np.float64(0.8493196534791204),
  np.float64(0.850750562573142),
  np.float64(0.8513589317324225),
  np.float64(0.8506977958603473),
  np.float64(0.8499342304869649),
  np.float64(0.8494003555104536),
  np.float64(0.8550060427638223),
  np.float64(0.8550432898552067),
  np.float64(0.8537551612781591),
  np.float64(0.8537551612781591),
  np.float64(0.8531809352859812),
  np.float64(0.854195918526209),
  np.float64(0.8496269419830427),
  np.float64(0.849220327902095),
  np.float64(0.8492575749934796),
  np.float64(0.8493227574034026),
  np.float64(0.8493196534791204),
  np.float64(0.8251028362306257),
  np.float64(0.8563903929936131),
  np.float64(0.8532864687115705),
  np.float64(0.8562972752651518),
  np.float64(0.8585321007482224),
  np.float64(0.8586252184766836),
  np.float64(0.8568870208787398),
  np.float64(0.8769383717407336),
  np.float64(0.8769383717407336),
  np.float64(0.8769383717407336),
  np.float64(0.8499342304869649),
  np.float64(0.8499342304869649),
  np.float64(0.8499342304869649),
  np.float64(0.8661677544820467),
  np.float64(0.8654538518971769),
  np.float64(0.8651124202261521),
  np.float64(0.8643053999128212),
  np.float64(0.8482891506174824),
  np.float64(0.8526036053695213),
  np.float64(0.8505239761005529),
  np.float64(0.8467371884764612),
  np.float64(0.8468923846905634),
  np.float64(0.8494065633590175),
  np.float64(0.8482891506174824),
  np.float64(0.8468303062049224),
  np.float64(0.8468303062049224),
  np.float64(0.8468303062049224),
  np.float64(0.8468303062049224),
  np.float64(0.857042217092842),
  np.float64(0.8562041575366904),
  np.float64(0.8552419410092573),
  np.float64(0.8555833726802822),
  np.float64(0.8559868828369476),
  np.float64(0.8600840628892434),
  np.float64(0.8549936270666939),
  np.float64(0.8842388016520973),
  np.float64(0.8842822565920461),
  np.float64(0.8843939978661995),
  np.float64(0.8854058771821455),
  np.float64(0.8851668750124282),
  np.float64(0.8841891388635849),
  np.float64(0.884133268226508),
  np.float64(0.884133268226508),
  np.float64(0.8756968020279168),
  np.float64(0.8756968020279168),
  np.float64(0.8606520810328574),
  np.float64(0.8606738085028315),
  np.float64(0.8571539583669955),
  np.float64(0.8571539583669955),
  np.float64(0.8569894503800473),
  np.float64(0.8569863464557651),
  np.float64(0.8569677229100728),
  np.float64(0.8569459954400988),
  np.float64(0.8569180601215604),
  np.float64(0.8493134456305563),
  np.float64(0.8493134456305563),
  np.float64(0.8493134456305563),
  np.float64(0.8501204659438875),
  np.float64(0.8501204659438875),
  np.float64(0.8501204659438875),
  np.float64(0.8501204659438875),
  np.float64(0.8501204659438875),
  np.float64(0.8501204659438875),
  np.float64(0.8508654077715776),
  np.float64(0.8552419410092573),
  np.float64(0.8503998191292712),
  np.float64(0.8504308583720916),
  np.float64(0.8499342304869649),
  np.float64(0.8499342304869649),
  np.float64(0.8499342304869649),
  np.float64(0.8499342304869649),
  np.float64(0.8499342304869649),
  np.float64(0.8499342304869649),
  np.float64(0.8499342304869649),
  np.float64(0.8499342304869649),
  np.float64(0.8499342304869649),
  np.float64(0.876007194456121),
  np.float64(0.8771866856832972),
  np.float64(0.8787541674457285),
  np.float64(0.8788721165684461),
  np.float64(0.8792632110279834),
  np.float64(0.8792632110279834),
  np.float64(0.8775001820357835),
  np.float64(0.8765814204482989),
  np.float64(0.8763982889156585),
  np.float64(0.8764541595527351),
  np.float64(0.8763920810670944),
  np.float64(0.8759885709104287),
  np.float64(0.8713513080330574),
  np.float64(0.8722824853176702),
  np.float64(0.8713513080330574),
  np.float64(0.8769383717407336),
  np.float64(0.8651434594689728),
  np.float64(0.8652055379546134),
  np.float64(0.8652055379546134),
  np.float64(0.8652055379546134),
  np.float64(0.8652055379546134),
  np.float64(0.8652055379546134),
  np.float64(0.8652986556830747),
  np.float64(0.8638398112705149),
  np.float64(0.8636535758135923),
  np.float64(0.863995007484617),
  np.float64(0.86421228218436),
  np.float64(0.8644605961269232),
  np.float64(0.8652986556830747),
  np.float64(0.8649882632548705),
  np.float64(0.8653607341687156),
  np.float64(0.8553040194948983),
  np.float64(0.8553040194948983),
  np.float64(0.8501825444295283),
  np.float64(0.8636846150564127),
  np.float64(0.8636846150564127),
  np.float64(0.8498100735156833),
  np.float64(0.8511758001997818),
  np.float64(0.8643985176412825),
  np.float64(0.8278653288416434),
  np.float64(0.8279274073272842),
  np.float64(0.8279274073272842),
  np.float64(0.8267479161001081),
  np.float64(0.8508033292859367),
  np.float64(0.8499342304869649),
  np.float64(0.8499342304869649),
  np.float64(0.8499342304869649),
  np.float64(0.8255373856301116),
  np.float64(0.8255373856301116),
  np.float64(0.8468303062049224),
  np.float64(0.8468303062049224),
  np.float64(0.8482891506174824),
  np.float64(0.8468303062049224),
  np.float64(0.8482891506174824),
  np.float64(0.8468303062049224),
  np.float64(0.8482891506174824),
  np.float64(0.8468303062049224),
  np.float64(0.8482891506174824),
  np.float64(0.8462095213485141),
  np.float64(0.8462095213485141),
  np.float64(0.8482891506174824),
  np.float64(0.8480718759177394),
  np.float64(0.8480718759177394),
  np.float64(0.8468303062049224),
  np.float64(0.8482891506174824),
  np.float64(0.8477614834895352),
  np.float64(0.8477614834895352),
  np.float64(0.8482891506174824),
  np.float64(0.8450300301213378),
  np.float64(0.8450921086069788),

In [20]:
non_dim_data = pd.DataFrame(column_final)

In [21]:

non_dim_data.to_excel('non_dim_final_formatted_data.xlsx')

PermissionError: [Errno 13] Permission denied: 'non_dim_final_formatted_data.xlsx'